### PR TITLE
fix(bridge): fix token approvals for bridge

### LINKED ISSUE #233: Bridge: fix recipient manual address override
manual override is slightly bugger after refactor

### PR DESCRIPTION
**Pull request by steezeburger**
Was originally for #233 but manual override worked fine, but I needed to fix the approvals flow.

Still closes #233. Added a test for manual override

### CODE REVIEW

File: apps/flame-defi/app/bridge/hooks/use-bridge-approval.ts [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+  const currency = chainConnection?.currency ?? null;
+
+  // only non-native evm currencies need approvals
+  const isErc20 =
+    currency && currency instanceof EvmCurrency && !currency.isNative;
+
+  const erc20Address = isErc20 ? currency.erc20ContractAddress : null;
+  const bridgeAddress = isErc20 ? currency.astriaIntentBridgeAddress : null;
+
+  const shouldEnableQuery = !!(
```
Comment (steezeburger) [inline apps/flame-defi/app/bridge/hooks/use-bridge-approval.ts:30]: bangbang redundant because return type of && expressions is already boolean

Comment (steezeburger) [inline apps/flame-defi/app/bridge/hooks/use-bridge-approval.ts:30]:
```suggestion
  const shouldEnableQuery = Boolean(
```

File: apps/flame-defi/app/bridge/components/submit-button/submit-button.tsx [hunk 2]
```diff
@@ -16,17 +23,68 @@ export const SubmitButton = ({
...
+    isCheckingApproval,
+    isApproving,
+  ]);
+
+  const isProcessing = isLoading || isCheckingApproval || isApproving;
+
+  const handleClick = async () => {
+    if (needsApproval) {
+      try {
+        await approveToken();
```
Comment (steezeburger) [inline apps/flame-defi/app/bridge/components/submit-button/submit-button.tsx:58]: TODO - should wait for transaction receipt
